# Rename this file to languages.toml to enable multilingual support
[en]
    languageName      = "English"
    languagedirection = "ltr"
    title             = "Stock Angler - 美股釣魚師"
    weight            = 1
